export const ADMIN = {
  loginTitle: 'ورود به پنل مدیریت',
  loginSubtitle: 'این بخش فقط برای مدیران مجاز است.',
  passwordLabel: 'گذرواژه',
  passwordPlaceholder: 'گذرواژه مدیر را وارد کنید',
  invalidPassword: 'گذرواژه نادرست است.',
  passwordNotConfigured: 'گذرواژه مدیر روی سرور تنظیم نشده است (ADMIN_PASSWORD).',
  databaseNotConfigured: 'دیتابیس روی سرور تنظیم نشده است (DATABASE_URL).',
  backendUnavailable: 'سرور در دسترس نیست. در محیط توسعه از «vercel dev» استفاده کنید.',
  loginButton: 'ورود',
  title: 'پنل مدیریت هم‌گرا',
  back: 'بازگشت به سامانه',
  refresh: 'به‌روزرسانی',
  tabTests: 'آزمون‌ها و زمان‌بندی',
  tabUsers: 'شرکت‌کنندگان',
  tabResults: 'نتایج',

  schedule: {
    intro: 'هر آزمون فقط در زمانی که اینجا تعیین می‌کنید برای شرکت‌کنندگان باز است. باز و بسته شدن را سرور انجام می‌دهد، نه ساعت دستگاه شرکت‌کننده؛ همهٔ زمان‌ها به وقت تهران است.',
    statusOpen: 'باز است',
    statusUpcoming: 'منتظر زمان شروع',
    statusClosed: 'بسته',
    statusEnded: 'پایان یافته',
    sessions: 'جلسهٔ ثبت‌شده',
    people: 'نفر',
    mode: 'وضعیت',
    modeClosed: 'بسته',
    modeOpen: 'باز (دستی)',
    modeScheduled: 'زمان‌بندی‌شده',
    modeHint: {
      closed: 'هیچ‌کس نمی‌تواند وارد شود.',
      open: 'همین حالا باز است و تا وقتی نبندید باز می‌ماند.',
      scheduled: 'در زمان شروع خودکار باز و در زمان پایان خودکار بسته می‌شود.',
    },
    opensAt: 'زمان شروع',
    closesAt: 'زمان پایان',
    closesOptional: 'بدون پایان (تا زمانی که دستی ببندید باز می‌ماند)',
    setTime: 'تعیین زمان',
    clearTime: 'حذف',
    grace: 'مهلت تکمیل بعد از پایان (دقیقه)',
    graceHint: 'کسی که پیش از پایان شروع کرده تا این مدت بعد از پایان هم می‌تواند ثبت نهایی کند.',
    allowRetake: 'اجازهٔ انجام مجدد',
    allowRetakeHint: 'اگر خاموش باشد هر نفر فقط یک‌بار می‌تواند ثبت نهایی کند.',
    showResult: 'نمایش نتیجه به شرکت‌کننده',
    showResultHint: 'اگر خاموش باشد فقط مدیر نتیجه را می‌بیند.',
    save: 'ذخیره',
    saved: 'ذخیره شد',
    openNow: 'باز کردن همین حالا',
    closeNow: 'بستن',
    notReady: 'مبنای امتیازدهی این آزمون هنوز تعریف نشده است؛ تا آن موقع قابل باز کردن نیست.',
    saveFailed: 'ذخیره انجام نشد. اتصال یا گذرواژه را بررسی کنید.',
    errors: {
      opens_at_required: 'برای حالت زمان‌بندی‌شده، زمان شروع لازم است.',
      closes_before_opens: 'زمان پایان باید بعد از زمان شروع باشد.',
      test_not_ready: 'این آزمون هنوز آمادهٔ باز شدن نیست.',
      invalid_grace: 'مهلت تکمیل باید بین ۰ تا ۲۴۰ دقیقه باشد.',
    } as Record<string, string>,
    summaryClosed: 'برای شرکت‌کنندگان دیده نمی‌شود و کسی نمی‌تواند وارد شود.',
    summaryOpen: 'برای همه باز است تا زمانی که ببندید.',
    summaryScheduled: (from: string, to: string | null) => `از ${from}${to ? ` تا ${to}` : ' (بدون پایان)'}`,
    year: 'سال',
    month: 'ماه',
    day: 'روز',
    hour: 'ساعت',
    minute: 'دقیقه',
    tehranTime: 'به وقت تهران',
  },

  users: {
    total: 'نفر در فهرست',
    completedOf: 'انجام داده',
    noUsers: 'هنوز کسی به فهرست اضافه نشده است. با فایل اکسل یا به‌صورت تکی اضافه کنید.',
    search: 'جست‌وجو بر اساس نام یا شماره…',
    excelTitle: 'بارگذاری با فایل اکسل',
    excelHint: 'ستون‌های لازم: «نام»، «نام خانوادگی»، «کد ملی» و «تلفن همراه». ستون‌های دیگر نادیده گرفته می‌شود. اگر شماره تماس تکراری باشد، اطلاعات قبلی به‌روز می‌شود. این فهرست برای همهٔ آزمون‌ها مشترک است.',
    chooseFile: 'انتخاب فایل اکسل (.xlsx)',
    fileError: 'خواندن فایل ممکن نشد. فقط فایل .xlsx پذیرفته می‌شود.',
    missingColumns: 'ستون‌های زیر در سطر عنوان پیدا نشد:',
    colNames: { firstName: 'نام', lastName: 'نام خانوادگی', nationalId: 'کد ملی', mobile: 'تلفن همراه' },
    previewValid: 'ردیف معتبر',
    previewInvalid: 'ردیف دارای خطا (افزوده نمی‌شود)',
    row: 'ردیف',
    reasons: {
      name: 'نام یا نام خانوادگی خالی است',
      mobile: 'شماره تلفن همراه معتبر نیست',
      national_id: 'کد ملی معتبر نیست',
      duplicate: 'شماره تکراری در فایل',
    } as Record<string, string>,
    addPeople: 'افزودن به فهرست',
    added: 'افزوده شد',
    updated: 'به‌روزرسانی شد',
    addFailed: 'افزودن انجام نشد. اتصال یا گذرواژه را بررسی کنید.',
    singleTitle: 'افزودن تکی',
    firstName: 'نام',
    lastName: 'نام خانوادگی',
    mobile: 'تلفن همراه',
    nationalId: 'کد ملی',
    addSingle: 'افزودن',
    colName: 'نام و نام خانوادگی',
    colMobile: 'شماره تماس',
    colLastLogin: 'آخرین ورود',
    never: '—',
    done: 'انجام شد',
    notDone: '—',
    remove: 'حذف',
    removeTitle: 'حذف از فهرست',
    removeBody: 'این فرد دیگر نمی‌تواند وارد شود. پاسخ‌های ثبت‌شدهٔ او (اگر باشد) حذف نمی‌شود. ادامه می‌دهید؟',
  },

  results: {
    pickTest: 'آزمون',
    loadFailed: 'بارگذاری نتایج انجام نشد.',
    empty: 'هنوز جلسه‌ای برای این آزمون ثبت نشده است.',
  },
} as const;
